name: ci

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - uses: subosito/flutter-action@v1.4.0
        with:
          flutter-version: 1.22.4
          channel: "stable"

      - name: Install Dependencies
        run: flutter pub get

      - name: Format
        run: flutter format --set-exit-if-changed lib test

      - name: Analyze
        run: dartanalyzer --fatal-infos --fatal-warnings lib test

      - name: Run tests
        run: flutter test
